# Generated by Django 5.1.4 on 2025-01-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(blank=True, max_length=30, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
